[custom]
ruleset=🌐 ch3ng.top,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/ch3ng.top.list
ruleset=🌐 SpaceLink,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/SpaceLink.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/DNS/DNS.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/DIRECT.list
ruleset=🚀 GLOBAL,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/proxy.list
ruleset=🎮 VRChat,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/vrchat.list

;翻墙程序,编程相关
ruleset=👨‍💻 GITHUB,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=👨‍💻 PYTHON,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Python/Python.list
ruleset=👨‍💻 DOCKER,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Docker/Docker.list
ruleset=👨‍💻 UBUNTU,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Ubuntu/Ubuntu.list
ruleset=👨‍💻 HGFACE,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/huggingface.list
ruleset=👨‍💻 国外软件,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/program.list
ruleset=🚀 GLOBAL,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/taiwan.list
;openai,bing
;ruleset=🤖 openAI,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/openai.list
ruleset=🤖 openAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list
ruleset=Ⓜ️ 必应,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Bing/Bing.list
ruleset=🎶 YoutubeMusic,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTubeMusic/YouTubeMusic.list
ruleset=📹 Youtube,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list
ruleset=🎆 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=🎶 抖音,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/DouYin/DouYin.list
ruleset=🎶 Tiktok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=🎶 网易音乐,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/NetEaseMusic.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/BanProgramAD.list
ruleset=Ⓜ️ 微软云盘,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OneDrive/OneDrive.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=📲 电报消息,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list
ruleset=🎮 SteamRegion,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/steamRegion.list
ruleset=🎮 SteamCN,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Steam/Steam.list
ruleset=🎮 Steam,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/steam.list
ruleset=🎮 深岩银河,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/DEEP_ROCK.list
ruleset=🎮 Epic,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Epic/Epic.list
ruleset=🎮 Epic,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/epic.list
ruleset=🎮 其他游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Origin/Origin.list
ruleset=🎮 其他游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Sony/Sony.list
ruleset=🎮 其他游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Nintendo/Nintendo.list
ruleset=🎮 其他游戏平台,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/ebd7226ce26bb64a63e5d772e91c6dfc2c98549d/rule/Clash/Game/Game.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list
ruleset=🎥 奈飞视频,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix_IP.txt
ruleset=🎥 Amazon,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list
ruleset=🎥 Amazon,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.list
ruleset=📺 哔哩哔哩东南亚,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BiliBiliIntl/BiliBiliIntl.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/LM-Firefly/Rules/refs/heads/master/Global-Services/BiliBiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BiliBili/BiliBili.list
ruleset=📺 AppleTV,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AppleTV/AppleTV.list
ruleset=🌏 国内媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ChinaMedia.list
ruleset=🌏 东南亚媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AsianMedia/AsianMedia.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ProxyMedia.list
ruleset=🚀 GLOBAL,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=🚀 GLOBAL,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Proxy/Proxy.list
ruleset=🌍 国外学术,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GlobalScholar/GlobalScholar.list
ruleset=⬇️ 下载工具,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Download/Download.list
ruleset=⬇️ 下载工具,https://raw.githubusercontent.com/szkane/ClashRuleSet/refs/heads/main/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Direct/Direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/WeChat/WeChat.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/LocalNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Lan/Lan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/ASN.China.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/China/China.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/ChinaIPs/ChinaIPs.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIpV6.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/CN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/ChinaDNS.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/ChinaNet.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xianyu-one/subconverter_configs/main/rule-list/6.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xianyu-one/subconverter_configs/main/rule-list/remote.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xianyu-one/subconverter_configs/main/rule-list/cn-cloud.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xianyu-one/subconverter_configs/main/rule-list/cn-dbsoft.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xianyu-one/subconverter_configs/main/rule-list/plex-noproxy.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xianyu-one/subconverter_configs/main/rule-list/xianyudomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/xianyu-one/subconverter_configs/main/rule-list/UnBan.list
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
;去广告
;ruleset=🚫 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AdvertisingTest/AdvertisingTest.list
;去小米电视广告
ruleset=🚫 广告拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/AdvertisingMiTV/AdvertisingMiTV.list
ruleset=🚫 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🚫 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🐟 漏网之鱼,https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/Ruleset/FINAL.list
ruleset=🐟 漏网之鱼,[]FINAL

;设置分组标志位
custom_proxy_group=🚀 GLOBAL`select`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50

custom_proxy_group=🎆 Google系`select`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇯🇵 日本🔗
custom_proxy_group=👨‍💻 编程相关`select`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇯🇵 日本🔗

custom_proxy_group=🤖 openAI`select`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=👨‍💻 GITHUB`select`[]👨‍💻 编程相关`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇯🇵 日本🔗
custom_proxy_group=👨‍💻 PYTHON`select`[]👨‍💻 编程相关`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇯🇵 日本🔗
custom_proxy_group=👨‍💻 DOCKER`select`[]👨‍💻 编程相关`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇯🇵 日本🔗
custom_proxy_group=👨‍💻 UBUNTU`select`[]👨‍💻 编程相关`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇯🇵 日本🔗
custom_proxy_group=👨‍💻 HGFACE`select`[]👨‍💻 编程相关`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇯🇵 日本🔗
custom_proxy_group=👨‍💻 国外软件`select`[]👨‍💻 编程相关`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇯🇵 日本🔗
custom_proxy_group=🌐 ch3ng.top`select`[]🇯🇵 日本🔗`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换
custom_proxy_group=🌐 SpaceLink`select`[]🇯🇵 日本🔗`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换
custom_proxy_group=Ⓜ️ 必应`select`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]DIRECT`[]🇯🇵 日本🔗
custom_proxy_group=🎆 Google`select`[]🎆 Google系`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=📹 Youtube`select`[]🎆 Google系`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🎶 YoutubeMusic`select`[]🎆 Google系`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🎶 抖音`select`[]DIRECT`[]REJECT
custom_proxy_group=🎶 Tiktok`select`[]🇯🇵 日本🔗`[]DIRECT
custom_proxy_group=🎶 网易音乐`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`(网易|音乐|解锁|Music|NetEase)
custom_proxy_group=Ⓜ️ 微软云盘`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=📲 电报消息`select`[]♻️ 自动选择`[]🇯🇵 日本🔗
custom_proxy_group=🎥 奈飞视频`select`[]🇯🇵 日本🔗
custom_proxy_group=🎥 Amazon`select`[]🇯🇵 日本🔗
custom_proxy_group=📺 哔哩哔哩`select`[]DIRECT
custom_proxy_group=📺 哔哩哔哩东南亚`select`[]DIRECT
custom_proxy_group=📺 AppleTV`select`[]🇯🇵 日本🔗
custom_proxy_group=🌏 东南亚媒体`select`[]🇯🇵 日本🔗
custom_proxy_group=🌍 国外媒体`select`[]🚀 GLOBAL`[]♻️ 自动选择`[]DIRECT`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🌏 国内媒体`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🌍 国外学术`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🚫 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=⬇️ 下载工具`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🐟 漏网之鱼`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🎮 SteamRegion`select`[]🚀 GLOBAL`[]DIRECT`[]🇯🇵 日本🔗
custom_proxy_group=🎮 SteamCN`select`[]DIRECT`[]🎮 SteamRegion`[]🇯🇵 日本🔗
custom_proxy_group=🎮 Steam`select`[]🎮 SteamRegion`[]DIRECT`[]🇯🇵 日本🔗
custom_proxy_group=🎮 深岩银河`select`[]DIRECT`[]🎮 SteamRegion`[]🇯🇵 日本🔗
custom_proxy_group=🎮 Epic`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🎮 其他游戏平台`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗
custom_proxy_group=🎮 VRChat`select`[]DIRECT`[]🚀 GLOBAL`[]♻️ 自动选择`[]🚀 手动切换`[]🇯🇵 日本🔗

custom_proxy_group=🇯🇵 日本🔗`url-test`(?=.*(🇯🇵|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan))^((?!免费).)*$`http://www.gstatic.com/generate_204`300,,50

;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/rule_base/clash.yaml
surge_rule_base=https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/rule_base/surge.conf
surfboard_rule_base=https://raw.githubusercontent.com/CH3NGYZ/clash-rules/refs/heads/main/rule_base/surge.conf
;luck
